name: Check Packages
on:
  push:
    branches:
      - main
      - axios-only
env:
  SERVICE_ID: ${{ vars.SERVICE_ID }}
  PATH_TO_PACKAGE_JSON: ${{ vars.PATH_TO_PACKAGE_JSON }}
  WEBHOOK_URL: ${{ vars.WEBHOOK_URL }}

jobs:
  Ingest-Webhook-to-Port:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.0.0
      - name: Ingest it all
        run: |
          sh ./ingest.sh